language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
env:
  - DJANGO_VERSION=1.9.9
  - DJANGO_VERSION=1.10.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script:
  - python setup.py test
  